author: 'Y Media Labs'
author_url: https://yml.co
min_acl: public
hide_documentation_coverage: false
theme: fullwidth
output: ./docs
documentation: ./*.md
swift_build_tool: xcodebuild
module: YPersistence
xcodebuild_arguments:
  - -scheme
  - YPersistence
  - -sdk
  - iphonesimulator
  - -destination
  - 'platform=iOS Simulator,name=iPhone 13'
